# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c16171d7191fe72faf8dc4743aa98414a9b7c518aabf51766829fd0d379d363914c62d946f6918f70fda9e64625e7f4f53774267e8545655fdf2858fc6cc04f4

test:
  secret_key_base: 3d9da4cb439d651a5a5b99801d103d0151ee5c4784959bd5fff90bbf4588d528e7181ec9a670f70938b5bf268aaf6361cc6e6768e7e987ebe0ea7c25df4ebb79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
